name: calendar_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^28.2.4
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  awesome_notifications: ^0.7.5-dev.1
  permission_handler: ^10.2.0
  fluttercontactpicker: ^5.0.0  # UPDATED: correct dependency name
  contacts_service: ^0.6.3  # NEW: dependency to fetch contacts
  cupertino_icons: ^1.0.8

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
